version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mynetwork
  flask-app:
    image: ${REPOSITORY}:latest
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
  nginx:
    image: nginx:latest
    ports:
      - "80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork: