version: "3.8"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - network
  flask-app:
    image: flask-app:latest
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - network
  nginx:
    image: nginx:latest
    depends_on:
      - flask-app
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    networks:
        - network
networks:
  network: