version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mynetwork
  flask-app:
    build: .
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: password
      SECRET_KEY: ${SECRET_KEY}
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    depends_on:
      - flask-app
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork: