version: '3.8'
services:
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mynetwork
  flask-app:
    build: .
    depends_on:
      - database
    networks:
      - mynetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    depends_on:
      - flask-app
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - mynetwork
networks:
  mynetwork: